// example.kotlin.angular/client/src/angular/src/app/addressBookList/addressBookList.component.ts
import { Component, OnInit, Input } from '@angular/core';
import {Router} from "@angular/router";

import {UserApiService} from "../services/userApi.service";

import * as info_js from 'example.kotlin.angular-information';
import info = info_js.net.akehurst.kotlin.example.addressbook.information;

@Component({
  selector: 'app-addressBook-list',
  templateUrl: './addressBookList.component.html',
  styleUrls: ['./addressBookList.component.scss']
})
export class AddressBookListComponent implements OnInit {

  addressBookList : string[];

  constructor(
    private userApi:UserApiService,
    private router: Router
  ) { }

  ngOnInit() {
    this.userApi.userNotification.notifyCreatedAddressBookSubject.subscribe(title => {
      this.addressBookList.push(title);
    });
    this.userApi.userNotification.notifyReadAllAddressBookSubject.subscribe( titles=>{
      this.addressBookList  = titles.toArray();
    });
    this.userApi.userNotification.notifyDeletedAddressBookSubject.subscribe(title => {
      let i = this.addressBookList.indexOf(title);
      this.addressBookList.splice(i,1);
    });
    this.userApi.userRequest.requestReadAllAddressBookTitles(this.userApi.session)
  }

  createAddressBook() {
    let newTitle = 'new Address Book'; //TODO: use a dialog to get the value
    this.userApi.userRequest.requestCreateAddressBook(this.userApi.session,newTitle);
  }

  readAddressBook(title:string) {
    this.router.navigate(['/addressBook'], {queryParams: {title: title}});
  }

  deleteAddressBook(title:string) {
    this.userApi.userRequest.requestDeleteAddressBook(this.userApi.session,title);
  }


}

<section>
  <header>
    <h1>Address Books</h1>
  </header>
  <article>
    <table>
      <thead>
      <tr>
        <th><button class="add" (click)="createAddressBook()" ></button></th>
        <th>Address Book</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let addressBook of addressBookList">
        <td><button class="delete" (click)="deleteAddressBook(addressBook)" ></button></td>
        <td (click)="readAddressBook(addressBook)">{{addressBook}}</td>
      </tr>
      </tbody>
    </table>

  </article>
</section>

// net.akehurst.kotlin.example.addressbook/client-react/src/react/src/addressBookList/AddressBookList.tsx
import React from 'react';

import userApi from '../services/userApi.service'

class AddressBookListState {

    addressBookList : string[] = [];

}

export default class AddressBookList extends React.Component<{}, AddressBookListState> {

    constructor(props: Readonly<{}>) {
        super(props);
        this.state = new AddressBookListState();
    }

    render() {
        const elements = this.state.addressBookList.map((ab) =>
            <tr key={ab.toString()}>
                <td>
                    <button className="remove" onClick={this.onRemove}>
                        <i className="pi pi-minus"/>
                    </button>
                </td>
                <td className="click">{ab}</td>
            </tr>
        );
        return (
            <section>
                <header>
                    <h1>Address Books</h1>
                </header>
                <article>
                    <table>
                        <thead>
                        <tr>
                            <th>
                                <button className="add" onClick={this.onAdd}>
                                    <i className="pi pi-plus"/>
                                </button>
                            </th>
                            <th>Address Book</th>
                        </tr>
                        </thead>
                        <tbody>
                            {elements}
                        </tbody>
                    </table>

                </article>
            </section>
        );
    }

    componentDidMount() {
        userApi.userNotification.notifyCreatedAddressBookSubject.subscribe(title => {
            //this.setState({addressBookList.push(title)});
        });
        userApi.userNotification.notifyReadAllAddressBookSubject.subscribe( titles=>{
           // this.addressBookList  = titles.toArray();
        });
        userApi.userNotification.notifyDeletedAddressBookSubject.subscribe(title => {
           // let i = this.addressBookList.indexOf(title);
           // this.addressBookList.splice(i,1);
        });
        userApi.userRequest.requestReadAllAddressBookTitles(userApi.session)
    }

    onAdd(): void {
    }

    onRemove(): void {
    }

};
